version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d:z